Repository Meong-Road/FE, pull requests merged in 2025-09, with the labels that each got.

#3 [DOCS] PR 템플릿 수정
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE/test.md
Labels: 📖 DOCS

#13 [FIX] mocks폴더 msw resetup
  .github/workflows/deploy-production.yml
  README.md
  components.json
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(gatherings)/quick/create/page.tsx
  src/app/(gatherings)/quick/page.tsx
  src/app/(gatherings)/regular/create/page.tsx
  src/app/(gatherings)/regular/detail/[id]/page.tsx
  src/app/favorites/page.tsx
  src/app/globals.css
  src/app/profile/[id]/page.tsx
  src/app/review/page.tsx
  src/components/__tests__/component.test.tsx
  src/components/form/SignupForm.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/lib/utils.ts
  src/mocks/browser.ts
  src/mocks/handlers/auth.ts
  src/mocks/handlers/gatherings.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/pets.ts
  src/mocks/handlers/reviews.ts
  src/mocks/handlers/users.ts
  src/mocks/server.ts
  tsconfig.json
  vercel.json
Labels: 🐞 BUG

#25 [FEAT] Signup Page 구축
  package.json
  pnpm-lock.yaml
  src/app/(auth)/signup/_api/customFetch.ts
  src/app/(auth)/signup/_api/signup.ts
  src/app/(auth)/signup/_components/Form/Form.tsx
  src/app/(auth)/signup/_components/Form/FormControl.tsx
  src/app/(auth)/signup/_components/Form/FormDescription.tsx
  src/app/(auth)/signup/_components/Form/FormField.tsx
  src/app/(auth)/signup/_components/Form/FormInput.tsx
  src/app/(auth)/signup/_components/Form/FormItem.tsx
  src/app/(auth)/signup/_components/Form/FormLabel.tsx
  src/app/(auth)/signup/_components/Form/FormMessage.tsx
  src/app/(auth)/signup/_components/Form/FormSubmitButton.tsx
  src/app/(auth)/signup/_components/Form/FormTitle.tsx
  src/app/(auth)/signup/_components/Form/index.ts
  src/app/(auth)/signup/_components/Form/types.ts
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/(auth)/signup/_hooks/useSignupForm.ts
  src/app/(auth)/signup/_hooks/useSignupMutation.ts
  src/app/(auth)/signup/page.tsx
  src/app/(gatherings)/quick/_components/QuickGatheringCard.tsx
  src/components/__tests__/Header.test.tsx
  src/components/form/SignupForm.tsx
  src/components/ui/form.tsx
  src/components/ui/sonner.tsx
  src/mocks/handlers/auth.ts
Labels: ✨ FEAT

#36 [Feat] signup 폼 크기 조절 및
  src/app/(auth)/signup/_api/signup.ts
  src/app/(auth)/signup/_components/Form/Form.tsx
  src/app/(auth)/signup/_components/Form/FormLabel.tsx
  src/app/(auth)/signup/_components/Form/FormLoginLink.tsx
  src/app/(auth)/signup/_components/Form/FormSocialButtons.tsx
  src/app/(auth)/signup/_components/Form/FormSubmitButton.tsx
  src/app/(auth)/signup/_components/Form/FormTitle.tsx
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/(auth)/signup/page.tsx
  src/assets/images/image.png
  src/components/ui/input.tsx
Labels: 🎨 DESIGN
